//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by VideoEditing.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDD_PARAM_SYSTEM                101
#define IDD_PARAM_GRABCUT               103
#define IDD_DIALOG_PLAY                 110
#define IDR_MAINFRAME                   128
#define IDR_VideoEditingTYPE            129
#define IDR_TOOLBAR_PLAY                130
#define IDD_PRA_DIALOG                  130
#define IDD_PARAM_CLOSEDFORM            131
#define IDD_PARAM_CLASSIFIER            132
#define IDD_MULTILAYER_DLG              133
#define IDB_SLIDER_HOVER                134
#define IDD_DIALOG_EDITLAYER            134
#define IDB_SLIDER_NORMAL               135
#define IDD_DIALOG2                     135
#define IDD_DIALOG_MATTING_PARAM        135
#define IDD_DIALOG_TRIMAPWIDTH          136
#define IDD_TEMPORAL_MATTING_DIALOG     138
#define IDB_PLAYBAR_MENU                140
#define IDD_DIALOG_TEMPORAL_REFINE      140
#define IDB_PLAYBAR_MENU_DISABLE        141
#define IDI_ICON1                       141
#define IDD_DIALOG_ROTOSCOPE            144
#define IDC_EDIT1                       1000
#define IDC_EDIT2                       1001
#define IDC_EDIT3                       1002
#define IDC_EDIT4                       1003
#define IDC_EDIT5                       1004
#define IDC_EDIT_CF_LEVEL               1005
#define IDC_EDIT_CF_ACTIVELEVEL         1006
#define IDC_EDIT_CF_WINSIZE             1007
#define IDC_EDIT_CF_THRESHOLD           1008
#define IDC_EDIT_CF_EPSILON             1009
#define IDC_SCROLLBAR1                  1011
#define IDC__CF_SCROLLBAR1              1011
#define IDC_BUTTON_OBJECTDIR            1012
#define IDC_BUTTON_ALPHADIR             1013
#define IDC_EDIT_OBJECTDIR              1014
#define IDC_EDIT_ALPHADIR               1015
#define IDC_EDIT_ITERATETIME            1018
#define IDC_EDIT_OUT                    1019
#define IDC_SLIDER1                     1020
#define IDC_EDIT_PolygonPointRadius     1020
#define IDC_SLIDER2                     1021
#define IDC_BUTTON1                     1021
#define IDC_BUTTON_ResetPara            1021
#define IDC_ROTOSCOPE                   1021
#define IDC_ROTOSCOPE_SAVEMASK          1021
#define IDC_SLIDER3                     1022
#define IDC_BUTTON2                     1022
#define IDC_SLIDER4                     1023
#define IDC_SLIDER5                     1024
#define IDC_LIST1                       1028
#define IDC_SLIDER_Cutoff               1028
#define IDC_BUTTON_EDIT                 1029
#define IDC_BUTTON_MERGE                1030
#define IDC_NAME_EDIT                   1031
#define IDC_DEPTH_EDIT                  1032
#define IDC_CHECK_ENABLE_DEPTH          1033
#define IDC_EDIT_DEPTH                  1034
#define IDC_EDIT_WIDTH                  1035
#define IDC_EDIT_MAT_LAYER_NAME         1036
#define IDC_EDIT_MAT_SFRAME             1037
#define IDC_EDIT_MAT_EFRAME             1038
#define IDC_COMBO_ALGORITHM             1039
#define IDC_RADIO_MAT_PART              1040
#define IDC_RADIO2                      1041
#define IDC_RADIO_MAT_WHOLE             1041
#define IDC_EDIT_PolygonThreshold       1042
#define IDC_EDIT_PolygonLineDiff        1043
#define IDC_EDIT_VideoWinSize           1044
#define IDC_EDIT_UpdateWinSize          1045
#define IDC_SLIDER_BoundSize            1046
#define IDC_SLIDER_PolygonCosThreshold  1047
#define IDC_SLIDER_PolygonDisThreshold  1048
#define IDC_SLIDER_Epsilon              1050
#define IDC_SLIDER_ForeThres            1051
#define IDC_SLIDER_BackThres            1052
#define IDC_EDIT_BoundSize              1053
#define IDC_EDIT_Cutoff                 1054
#define IDC_EDIT_Epsilon                1055
#define IDC_EDIT_ForeThres              1056
#define IDC_EDIT_BackThres              1057
#define IDC_RADIO_IMGWHOLE              1058
#define IDC_EDIT_CosThreshold           1058
#define IDC_CHECK_FRAME_MAT             1059
#define IDC_EDIT_Cutoff2                1059
#define IDC_EDIT_DisThreshold           1059
#define IDC_COMBO_ALGO                  1060
#define IDC_RADIO_IMPART                1061
#define IDC_EDIT_TM_TEMWEIGHT           1090
#define IDC_EDIT_TM_LAYERNAME           1091
#define IDC_EDIT_TM_SFRAME              1092
#define IDC_EDIT_TM_EFRAME              1093
#define IDC_EDIT_TM_STEP                1094
#define IDC_EDIT_TM_SWEIGHT             1095
#define IDC_COMBO_LAYERTYPE             1096
#define IDC_SLIDER_TRIMAPALPHA          1097
#define IDC_EDIT_TRIMAPALPHA            1098
#define IDC_CHECK_ANCHOR_FIRST          1099
#define IDC_CHECK_ANCHOR_FIRST2         1100
#define IDC_CHECK_ANCHOR_LAST           1100
#define IDC_EDIT_LAYER_NAME             1100
#define IDC_EDIT_START_FRAME_REFINE     1101
#define IDC_EDIT_END_FRAME_REFINE       1102
#define IDC_CHECK1                      1103
#define IDC_CHECK_OPTICAL_GLOBAL        1103
#define IDC_CHECk_PREVIEW               1103
#define IDC_KD                          1110
#define IDC_KL                          1110
#define IDC_KU                          1111
#define IDC_STARTINDEX                  1112
#define IDC_ENDINDEX                    1113
#define IDC_SAVE_START                  1114
#define IDC_EDIT_FRAMEINDEX             1115
#define IDC_EDIT_FRAMETOTAL             1116
#define IDC_EDIT_PYR_LEVEL              1117
#define IDC_SAVE_END                    1118
#define IDC_EDIT_LB                     1119
#define IDC_EDIT_BMIN                   1120
#define IDC_EDIT_BMAX                   1121
#define IDC_EDIT_LS                     1122
#define IDC_BUTTON_EXPORT               1123
#define IDC_BUTTON_IMPORT               1124
#define ID_SEL_RECT                     32773
#define ID_SEL_FORE                     32776
#define ID_SEL_BACK                     32778
#define ID_GRABBER_RECTANGLEGRAB        32779
#define ID_GRABBER_FOREGROUNDBRUSH      32780
#define ID_GRABBER_BACKGROUNDBRUSH      32781
#define ID_VIEW_EDITWINDOW              32782
#define ID_VIEW_RESULTWINDOW            32783
#define ID_RUN_RUN                      32784
#define ID_PLAY_PAUSE                   32785
#define ID_PLAY_STOP                    32786
#define ID_PLAY_TOSTART                 32787
#define ID_PLAY_TOEND                   32788
#define ID_TOOL_DEPTHRECONSTRUCTION     32788
#define ID_VIEW_PICWINDOW               32788
#define ID_PLAY_STEPLAST                32789
#define ID_RUN_MODE                     32789
#define ID_PLAY_STEPNEXT                32790
#define ID_MODE_PICTURE                 32790
#define ID_PLAY_FORWARD                 32791
#define ID_MODE_VIDEO                   32791
#define ID_PLAY_BACKWARD                32792
#define ID_GRABBER_GRABCUT              32792
#define ID_GRABBER_CLOSEDFORMMATTING    32793
#define ID_SETTING_PREFERENCE           32794
#define ID_Menu                         32795
#define ID_VIEW_ZOOM                    32796
#define ID_EDIT_MOVE                    32797
#define ID_EDIT_ZOOM                    32798
#define ID_EDIT_FIT                     32799
#define ID_BUTTON32802                  32802
#define ID_BUTTON32803                  32803
#define ID_EDIT_ZOOMOUT                 32805
#define ID_EDIT_ZOOMIN                  32806
#define ID_RUN_STOP                     32807
#define ID_RUN_RUNVIDEO                 32813
#define ID_RUN_UPDATE                   32817
#define ID_UPDATE_GLOBALUPDATE          32818
#define ID_UPDATE_LOCALUPDATE           32819
#define ID_RUN_FRAME                    32820
#define ID_RUN_VIDEO                    32821
#define ID_GRABBER_A                    32822
#define ID_GRABBER_PEN                  32823
#define ID_GRABBER_BRUSH                32824
#define ID_BRUSH_FOREGROUNDBRUSH        32825
#define ID_BRUSH_BACKGROUNDBRUSH        32826
#define ID_PEN_FOREGROUND               32827
#define ID_PEN_BACKGROUND               32828
#define ID_BUTTON32833                  32833
#define ID_BUTTON32834                  32834
#define ID_VIEW_DOCKBAR                 32835
#define ID_SETTING_COLOR                32836
#define ID_BUTTON32837                  32837
#define ID_RUN_MATTING                  32838
#define ID_SETTING_LOCALWIN             32839
#define ID_VIEW_TRIMAP                  32840
#define ID_RUN_GETFINALLAYER            32841
#define ID_VIEW_DEPTH                   32842
#define ID_FILE_OPENPROJECT             32843
#define ID_RUN_REFINE                   32844
#define ID_PREPROCESS_OPTICALFLOW       32848
#define ID_HELP_TESTFILLHOLES           32849
#define ID_BUTTON32850                  32850
#define ID_PEN_UNKNOWN                  32850
#define ID_HELP_DEPTHCOMPOSITION        32850
#define ID_BUTTON_AddNewLayer           32856
#define ID_RUN_TEMPORALMATTING          32858
#define ID_POSTPROCESS_LAYEROPTICALFLOW 32860
#define ID_BUTTON32861                  32861
#define ID_BUTTON_TRIMAP_REFINE         32861
#define ID_RUN_GENERATEDEFLAYERDEPTH    32862
#define ID_RUN_GENERATEUNKNOWNOPTICALFLOW 32863
#define ID_BUTTON32865                  32865
#define ID_RUN_ROTOSCOPING              32869
#define ID_FILE_IMPORTROTOCURVES        32870
#define ID_FILE_EXPORTROTOCURVES        32871
#define ID_TOOLS_BASE                   40000
#define ID_BUTTON_POLYGON               40001
#define ID_BUTTON_BEIZER                40002
#define ID_TOOLS_END                    40100

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        145
#define _APS_NEXT_COMMAND_VALUE         32872
#define _APS_NEXT_CONTROL_VALUE         1124
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
